name: macOS build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '30 7 * * 1,5'
  workflow_dispatch: 
   
jobs:
  build:
    name: Build on macOS
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14.2'
        cache: 'pip'
        cache-dependency-path: '.github/workflows/nightly-mac.yml'

    - name: Rust Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Toolchain Cache
      id: mac-toolchain
      uses: actions/cache@v5
      with:
        path: ~/mac-toolchain
        key: ${{ runner.os }}-${{ runner.arch }}-toolchain

    - name: Get latest cargo-c version
      id: cargoc_version
      run: |
        VERSION=$(curl -sL -A "HandBrake-Nightly" "https://crates.io/api/v1/crates/cargo-c" | python3 -c "import sys, json; print(json.load(sys.stdin)['crate']['max_version'])")
        echo "CARGOC_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Cargo-C Toolchain Cache
      id: mac-cargo-c-toolchain
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-c-${{ env.CARGOC_VERSION }}

    - name: Download the Source Code
      run: |
        git clone https://github.com/HandBrake/HandBrake.git
        ./patch.sh

    - name: Setup Environment
      run: |
        echo ~/mac-toolchain/bin >> $GITHUB_PATH
        rustup target add x86_64-apple-darwin
        xcodebuild -downloadComponent MetalToolchain
        brew install ccache
        export PATH=$(brew --prefix ccache)/libexec:$PATH
        echo "PATH=$(brew --prefix ccache)/libexec:$PATH" >> $GITHUB_ENV

    - name: Compiler Cache
      uses: actions/cache@v5
      with:
        path: /Users/runner/Library/Caches/ccache
        key: ${{ runner.os }}-ccache-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Setup Toolchain
      if: steps.mac-toolchain.outputs.cache-hit != 'true'
      run: |
        pip install setuptools
        HandBrake/scripts/mac-toolchain-build ~/mac-toolchain

    - name: Setup Cargo-C Toolchain
      if: steps.mac-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c --version ${{ env.CARGOC_VERSION }} --locked

    - name: Build HandBrake
      run: |
        cd HandBrake
        ./configure --enable-libdovi
        cd build
        make ub && make pkg.create

    - name: Check Ccache Stats
      run: |
        echo "### Ccache Stats" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        ccache -s >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Upload Assets
      uses: actions/upload-artifact@v6
      with:
        name: HandBrake-macos
        path: ./HandBrake/build/pkg/*.dmg


  deploy_nightly:
    name: Deploy Nightly Build
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
       
      - name: Download Artifacts - Universal Binaries
        uses: actions/download-artifact@v5
        with:
          name: HandBrake-macos
          path: mac/
          
      # Generate Hashes
      - name: Generate SHA265 Hashes
        run: |
          cd mac
          sha256sum * > sha256.txt
          cp sha256.txt ../.github/workflows/
          cd ..
          cd .github/workflows/
          sed -e 's/  / | /' -i sha256.txt
          sed -e 's/^/| /'  -i sha256.txt
          sed -e 's/$/ |/' -i sha256.txt
          cat sha256.txt >> mac_rel_body.md
      
      # Publishing the Release
      - name: Remove the old Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 0
          delete_tag_pattern: "mac"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "mac/*.*"
          name: "Snapshots for macOS"
          bodyFile: .github/workflows/mac_rel_body.md
          prerelease: true
          replacesArtifacts: false
          allowUpdates: false
          tag: mac
          token: ${{ secrets.GITHUB_TOKEN }}
