name: Ubuntu Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '30 7 * * 1,5'
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6

    - name: Rust Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Get latest cargo-c version
      id: cargoc_version
      run: |
        VERSION=$(curl -sL -A "HandBrake-Nightly" "https://crates.io/api/v1/crates/cargo-c" | python3 -c "import sys, json; print(json.load(sys.stdin)['crate']['max_version'])")
        echo "CARGOC_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Cargo-C Toolchain Cache
      id: linux-cargo-c-toolchain
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: linux-cargo-c-toolchain-${{ env.CARGOC_VERSION }}

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install \
            autoconf automake build-essential libass-dev libbz2-dev libfontconfig1-dev \
            libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev \
            libmp3lame-dev libnuma-dev libturbojpeg0-dev libssl-dev libogg-dev libopus-dev \
            libsamplerate-dev libspeex-dev libtheora-dev libtool libtool-bin libvorbis-dev \
            libx264-dev libxml2-dev libvpx-dev make nasm ninja-build patch tar zlib1g-dev \
            appstream gettext libglib2.0-dev libgtk-4-dev python3-mesonpy libva-dev \
            libdrm-dev ccache

        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21 all
        
        mkdir -p $HOME/llvm-overrides
        
        ln -sf $(which llvm-ar-21) $HOME/llvm-overrides/ar
        ln -sf $(which llvm-nm-21) $HOME/llvm-overrides/nm
        ln -sf $(which llvm-ranlib-21) $HOME/llvm-overrides/ranlib
        
        ln -sf $(which lld-21) $HOME/llvm-overrides/ld

        echo "PATH=$HOME/llvm-overrides:$PATH" >> $GITHUB_ENV

        mkdir -p $HOME/ccache_bin
        ln -s $(which ccache) $HOME/ccache_bin/clang-21
        ln -s $(which ccache) $HOME/ccache_bin/clang++-21
        
        echo "PATH=$HOME/ccache_bin:$HOME/llvm-overrides:$PATH" >> $GITHUB_ENV
        
        echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
        echo "CC=clang-21" >> $GITHUB_ENV
        echo "CXX=clang++-21" >> $GITHUB_ENV
        
        echo "AR=llvm-ar-21" >> $GITHUB_ENV
        echo "NM=llvm-nm-21" >> $GITHUB_ENV
        echo "RANLIB=llvm-ranlib-21" >> $GITHUB_ENV
        echo "LDFLAGS=-fuse-ld=lld-21" >> $GITHUB_ENV

    - name: Compiler Cache
      uses: actions/cache@v5
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Setup Cargo-C Toolchain
      if: steps.linux-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c --version ${{ env.CARGOC_VERSION }} --locked

    - name: Download the Source Code
      run: |
        git clone https://github.com/HandBrake/HandBrake.git
        ./patch.sh

    - name: Build HandBrake Linux
      run: |
        cd HandBrake
        ./configure --lto=on --enable-qsv --enable-vce --enable-nvenc --enable-nvdec --enable-libdovi --launch-jobs=0 --launch
        mv build/HandBrakeCLI ../HandBrakeCLI-$(date +'%Y%m%d')-master-x86_64
        mv build/gtk/src/ghb ../ghb-$(date +'%Y%m%d')-master-x86_64

    - name: Check Ccache Stats
      run: |
        echo "### Ccache Stats" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        ccache -s >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Upload HandBrake CLI
      uses: actions/upload-artifact@v6
      with:
        name: HandBrakeCLI
        path: ./HandBrakeCLI*

    - name: Upload HandBrake GUI
      uses: actions/upload-artifact@v6
      with:
        name: HandBrakeGUI
        path: ./ghb-*


  deploy_nightly:
    name: Deploy Nightly Build
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
       
      - name: Download Artifacts - CLI Ubuntu
        uses: actions/download-artifact@v7
        with:
          name: HandBrakeCLI
          path: ubuntu/

      - name: Download Artifacts - GUI Ubuntu
        uses: actions/download-artifact@v7
        with:
          name: HandBrakeGUI
          path: ubuntu/
          
      # Generate Hashes
      - name: Generate SHA265 Hashes
        run: |
          cd ubuntu
          sha256sum * > sha256.txt
          cp sha256.txt ../.github/workflows/
          cd ..
          cd .github/workflows/
          sed -e 's/  / | /' -i sha256.txt
          sed -e 's/^/| /'  -i sha256.txt
          sed -e 's/$/ |/' -i sha256.txt
          cat sha256.txt >> ubuntu_rel_body.md
      
      # Publishing the Release
      - name: Remove the old Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 0
          delete_tag_pattern: "ubuntu"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ubuntu/*"
          name: "Snapshots for Ubuntu"
          bodyFile: .github/workflows/ubuntu_rel_body.md
          prerelease: true
          replacesArtifacts: false
          allowUpdates: false
          tag: ubuntu
          token: ${{ secrets.GITHUB_TOKEN }}
