name: Arch Linux Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '30 7 * * 1,5'
  workflow_dispatch:

jobs:
  build:
    name: Build on Arch
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6

    - name: Rust Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Get latest cargo-c version
      id: cargoc_version
      run: |
        VERSION=$(curl -sL -A "HandBrake-Nightly" "https://crates.io/api/v1/crates/cargo-c" | python3 -c "import sys, json; print(json.load(sys.stdin)['crate']['max_version'])")
        echo "CARGOC_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Cargo-C Toolchain Cache
      id: linux-cargo-c-toolchain
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/cargo-capi
          ~/.cargo/bin/cargo-cbuild
          ~/.cargo/bin/cargo-cinstall
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-c-${{ env.CARGOC_VERSION }}

    - name: Setup Cargo-C Toolchain
      if: steps.linux-cargo-c-toolchain.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-c --version ${{ env.CARGOC_VERSION }} --locked

    - name: Build HandBrake Arch Linux
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.9

    - name: Upload HandBrake-SVT-AV1-PSY Archive
      uses: actions/upload-artifact@v6
      with:
        name: HandBrakePKG
        path: ${{ steps.makepkg.outputs.pkgfile0 }}


  deploy_nightly:
    name: Deploy Nightly Build
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
       
    - name: Download Artifacts - PKG Arch Linux
      uses: actions/download-artifact@v7
      with:
        name: HandBrakePKG
        path: arch/

    # Generate Hashes
    - name: Generate SHA265 Hashes
      run: |
        cd arch
        sha256sum * > sha256.txt
        cp sha256.txt ../.github/workflows/
        cd ..
        cd .github/workflows/
        sed -e 's/  / | /' -i sha256.txt
        sed -e 's/^/| /'  -i sha256.txt
        sed -e 's/$/ |/' -i sha256.txt
        cat sha256.txt >> arch_rel_body.md
      
    # Publishing the Release
    - name: Remove the old Release
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 0
        delete_tag_pattern: "arch"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "arch/*"
        name: "Snapshots for Arch Linux"
        bodyFile: .github/workflows/arch_rel_body.md
        prerelease: true
        replacesArtifacts: false
        allowUpdates: false
        tag: arch
        token: ${{ secrets.GITHUB_TOKEN }}
